#!/usr/bin/env bash
# WALTEUR reflect — the META self-optimization pass (run via /optimize or in CI).
# The per-build loop (recall → consolidate → lesson-gate → lesson-feedback) optimizes the LESSON store.
# This higher-order pass audits the ENGINE's OWN performance: which lessons demonstrably help (promote)
# vs hurt (prune), the eval-quality trend across builds (is it getting better?), and memory health.
# Emits a report whose recommendations feed _relay/ISSUES.md. Read-mostly — proposes, never auto-edits.
set -uo pipefail
MEM="${WALTEUR_MEM:-$HOME/.walteur/memory/lessons.jsonl}"
MDIR="$(dirname "$MEM")"; mkdir -p "$MDIR"
KIT="$(cd "$(dirname "$0")/.." 2>/dev/null && pwd || echo .)"   # walteur-kit/
SCORES="$KIT/eval/scores.jsonl"
OUT="$MDIR/self-optimization-report.md"
TS="$(date '+%Y-%m-%dT%H:%M:%S')"

cnt() { [ -f "$1" ] && { grep -c . "$1" 2>/dev/null || true; } || echo 0; }
total="$(cnt "$MEM")"; conflicts="$(cnt "$MDIR/conflicts.jsonl")"; retired="$(cnt "$MDIR/retired.jsonl")"
total="${total:-0}"; conflicts="${conflicts:-0}"; retired="${retired:-0}"

top="(no lessons have earned a positive score yet)"; prune="(none — no active lesson is net-harmful yet)"
if [ -s "$MEM" ]; then
  t="$(jq -rs 'map(select((.helpful//0)>0)) | sort_by(-((.helpful//0)-(.harmful//0))) | .[0:5][] | "- [net \((.helpful//0)-(.harmful//0)), used \(.applied//0)x] \(.lesson) (\(.id))"' "$MEM" 2>/dev/null || true)"
  [ -n "$t" ] && top="$t"
  p="$(jq -rs 'map(select(((.applied//0)>=2) and (((.harmful//0)-(.helpful//0))>=1)))[] | "- PRUNE? \(.lesson) (id \(.id): used \(.applied//0)x, net \((.helpful//0)-(.harmful//0)))"' "$MEM" 2>/dev/null || true)"
  [ -n "$p" ] && prune="$p"
fi

trend="(no eval runs recorded yet — run walteur-kit/eval/score.sh on the tasks)"
if [ -s "$SCORES" ]; then
  tr="$(jq -rs 'group_by(.task)[] | {task: .[0].task, first: (.[0].pass_k // .[0].score), last: (.[-1].pass_k // .[-1].score), runs: length} | "- \(.task): \(.first) → \(.last) over \(.runs) run(s) \(if (.last) > (.first) then "UP" elif (.last) < (.first) then "DOWN — investigate a recent gate/prompt edit" else "flat" end)"' "$SCORES" 2>/dev/null || true)"
  [ -n "$tr" ] && trend="$tr"
fi

{
  echo "# WALTEUR Self-Optimization Report — $TS"
  echo
  echo "> The engine auditing its OWN performance. Generated by reflect.sh (/optimize). Read-mostly; recommendations feed _relay/ISSUES.md."
  echo
  echo "## Memory health"
  echo "- Active lessons: **$total** · Retired (proved harmful): **$retired** · Conflicts held for review: **$conflicts**"
  echo
  echo "## Top lessons by earned score (helpful − harmful) — promote the strongest to canonical PLAN guidance"
  echo "$top"
  echo
  echo "## Prune candidates (active but trending net-harmful — verify, then retire or fix the root cause)"
  echo "$prune"
  echo
  echo "## Eval-quality trend (pass^k per task, first → latest run — is the engine getting better?)"
  echo "$trend"
  echo
  echo "## Recommended actions (codify into _relay/ISSUES.md)"
  [ "${conflicts:-0}" -gt 0 ] && echo "- Review **$conflicts** contradiction(s) in conflicts.jsonl (a held lesson contradicts a stored one)." || echo "- No contradictions to review."
  [ "${retired:-0}" -gt 0 ] && echo "- **$retired** lesson(s) auto-retired as harmful — sanity-check retired.jsonl in case the heuristic over-fired." || echo "- No lessons retired (store is healthy or young)."
  echo "- Promote the top positive-score lessons above into canonical guidance; prune/fix the net-harmful ones."
  echo "- Any eval task trending DOWN ⇒ a recent prompt/gate edit likely weakened it — bisect via scores.jsonl and add a regression case."
} > "$OUT"
echo "reflect: wrote $OUT (active=$total · retired=$retired · conflicts=$conflicts)"
exit 0
